// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJGvvihux7k0eDNeNcQxjpo-24ByIfO88',
    appId: '1:258574371181:web:2c20f2421dff20be83b264',
    messagingSenderId: '258574371181',
    projectId: 'cheating-detector-2e34d',
    authDomain: 'cheating-detector-2e34d.firebaseapp.com',
    storageBucket: 'cheating-detector-2e34d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMg1CF6gWzb9s76o_Ic0Vfwak0lJbIIPA',
    appId: '1:258574371181:android:852574d236eeee1183b264',
    messagingSenderId: '258574371181',
    projectId: 'cheating-detector-2e34d',
    storageBucket: 'cheating-detector-2e34d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaVoPhn0tF3evx-7zwL6JZzpobnYwFivs',
    appId: '1:258574371181:ios:03c3f71bf24e9aad83b264',
    messagingSenderId: '258574371181',
    projectId: 'cheating-detector-2e34d',
    storageBucket: 'cheating-detector-2e34d.appspot.com',
    iosClientId: '258574371181-dr46faeoke1sn2jrk2kdvgi3qq76torq.apps.googleusercontent.com',
    iosBundleId: 'com.matrix.aeye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaVoPhn0tF3evx-7zwL6JZzpobnYwFivs',
    appId: '1:258574371181:ios:03c3f71bf24e9aad83b264',
    messagingSenderId: '258574371181',
    projectId: 'cheating-detector-2e34d',
    storageBucket: 'cheating-detector-2e34d.appspot.com',
    iosClientId: '258574371181-dr46faeoke1sn2jrk2kdvgi3qq76torq.apps.googleusercontent.com',
    iosBundleId: 'com.matrix.aeye',
  );
}
